{"frames":[{"func":"filter(db2018[1:181, ])","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"filter.data.frame(db2018[1:181, ])","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"filter_rows(.data, ..., caller_env = caller_env())","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"DataMask$new(.data, caller_env)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"initialize(...)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"abort(\"Can't transform a data frame with duplicate names.\")","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"signal_abort(cnd)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(fallback)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error: Can't transform a data frame with duplicate names.\n\u001B[90mRun `rlang::last_error()` to see where the error occurred.\u001B[39m\n"}